#!/bin/sh

# Welcome to the civil laptop script!
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

# shellcheck disable=SC3043

fancy_echo() {
    local fmt="$1"
    shift

    # shellcheck disable=SC2059
    printf "\\n$fmt\\n" "$@"
}

append_to_zshrc() {
    local text="$1" zshrc
    local skip_new_line="${2:-0}"

    if [ -w "$HOME/.zshrc.local" ]; then
        zshrc="$HOME/.zshrc.local"
    else
        zshrc="$HOME/.zshrc"
    fi

    if ! grep -Fqs "$text" "$zshrc"; then
        if [ "$skip_new_line" -eq 1 ]; then
            printf "%s\\n" "$text" >>"$zshrc"
        else
            printf "\\n%s\\n" "$text" >>"$zshrc"
        fi
    fi
}

# shellcheck disable=SC2154
trap 'ret=$?; if [ $ret -ne 0 ] && [ $ret -ne 130 ] && [ $ret -ne 143 ]; then printf "failed\n\n" >&2; fi; exit $ret' EXIT

set -e

mkdir -p "$HOME/.bin"

if [ ! -f "$HOME/.zshrc" ]; then
    touch "$HOME/.zshrc"
fi

# shellcheck disable=SC2016
append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'

# Determine Homebrew prefix
arch="$(uname -m)"
if [ "$arch" = "arm64" ]; then
    HOMEBREW_PREFIX="/opt/homebrew"
else
    HOMEBREW_PREFIX="/usr/local"
fi

update_shell() {
    local shell_path="$HOMEBREW_PREFIX/bin/zsh"

    fancy_echo "Changing your shell to zsh ..."
    if ! grep "$shell_path" /etc/shells >/dev/null 2>&1; then
        fancy_echo "Adding '$shell_path' to /etc/shells"
        sudo sh -c "echo $shell_path >> /etc/shells"
    fi
    sudo chsh -s "$shell_path" "$USER"
}

# checks architecture
if [ "$arch" = "arm64" ]; then
    # checks if Rosetta is already installed
    if ! pkgutil --pkg-info=com.apple.pkg.RosettaUpdateAuto >/dev/null 2>&1; then
        echo "Installing Rosetta"
        # Installs Rosetta2
        softwareupdate --install-rosetta --agree-to-license
    else
        echo "Rosetta is installed"
    fi
fi

gem_install_or_update() {
    if gem list "$1" --installed >/dev/null; then
        gem update "$@"
    else
        gem install "$@"
    fi
}

if ! command -v brew >/dev/null; then
    fancy_echo "Installing Homebrew ..."
    /bin/bash -c \
        "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    append_to_zshrc "eval \"\$($HOMEBREW_PREFIX/bin/brew shellenv)\""

    export PATH="$HOMEBREW_PREFIX/bin:$PATH"
fi

fancy_echo "Updating Homebrew formulae ..."
brew update --force # https://github.com/Homebrew/brew/issues/1151
brew bundle --file=- <<EOF
tap "thoughtbot/formulae"
tap "heroku/brew"

# Unix
brew "universal-ctags"
brew "git"
brew "openssl"
brew "rcm"
brew "reattach-to-user-namespace"
brew "shfmt"
brew "tmux"
brew "vim"
brew "watchman"
brew "xsv"
brew "zsh"
brew "zsh-completions"
brew "zplug"

# Heroku
brew "heroku/brew/heroku"
brew "parity"

# GitHub
brew "gh"

# Image manipulation
brew "imagemagick"

# Programming language prerequisites and package managers
brew "autoconf"
brew "automake"
brew "coreutils"
brew "libtool"
brew "libyaml" # should come after openssl
brew "unixodbc"

# Encryption / signing
cask "gpg-suite-no-mail"

# Databases
# Update .zshrc accordingly
# export PATH="/usr/local/opt/postgresql@VV/bin:$PATH"
brew "postgresql@16"
brew "postgresql@17"

# Start: customization

brew "aha"
brew "awscli"
brew "bat"
brew "eza"
brew "fd"
brew "fzf"
brew "git-cliff"
brew "git-delta"
brew "glow"
brew "graphviz"
brew "gum"
brew "httpie"
brew "jq"
brew "pgformatter"
brew "rg"
brew "terminal-notifier"
brew "tldr"
brew "tree"
brew "wxwidgets@3.2"

cask "iterm2"
cask "visual-studio-code"

# End: customization
EOF

# Now that Homebrew's zsh is installed, register it as the login shell.
if [ "$SHELL" != "$HOMEBREW_PREFIX/bin/zsh" ]; then
    update_shell
fi

if [ "$LAPTOP_SLIM" != "true" ]; then

    brew bundle --file=- <<EOF
# Start: customization

# Desktop Apps
cask "1password"
cask "1password-cli"
cask "appzapper"
cask "balsamiq-wireframes"
cask "calibre"
cask "carbon-copy-cloner"
cask "dash"
cask "ddpm" # Dell Display and Peripheral Manager
cask "deckset"
cask "divvy"
cask "drawio"
cask "google-chrome"
cask "google-drive"
cask "grammarly-desktop"
cask "keybase"
cask "keycastr"
cask "monodraw"
cask "netdownloadhelpercoapp"
cask "ngrok"
cask "obsidian"
cask "raycast"
cask "slack"
cask "sourcetree"
cask "stay"
cask "typora"
cask "wkhtmltopdf"
cask "zoom"

# End: customization
EOF

fi

fancy_echo "Update heroku binary ..."
brew unlink heroku
brew link --force heroku

fancy_echo "Configuring mise version manager ..."
if command -v mise &> /dev/null; then
    fancy_echo "... already installed, skipping."
else
    brew install mise
    append_to_zshrc 'eval "$(mise activate zsh)"' 1
fi

# Start: Customizations

mkdir -p "$HOME/Workspaces"

# `brew search font-`
brew install font-caveat
brew install font-fira-code-nerd-font
brew install font-inter

# End: Customizations

if [ -f "$HOME/.laptop.local" ]; then
    fancy_echo "Running your customizations from ~/.laptop.local ..."
    # shellcheck disable=SC1091
    . "$HOME/.laptop.local"
fi
