#!/bin/sh

brew bundle --file=- <<EOF
brew "ctags"
brew "jsonpp"
brew "mysql"
brew "mysql-utilities"
brew "vim"
brew "yarn"

cask "gpg-suite"
cask "appzapper"
cask "balsamiq-mockups"
cask "carbon-copy-cloner"
cask "dash"
cask "dropbox"
cask "evernote"
cask "google-drive-file-stream"
cask "postman"
cask "sequel-pro"
cask "slack"
cask "stay"
EOF
